name: "🐛 Report a bug or feedback"
description: "Report a problem or feedback about the website."
title: "[Bug]: "
labels: ["bug: unconfirmed"]
body:
  - type: input
    attributes:
      label: What is your wallet address?
      placeholder: |
        0x0000000000000000000000000000000000000000
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe your issue or feedback
      placeholder: |
        Your answer
    validations:
      required: true
  - type: input
    attributes:
      label: Please attach a screenshot or a video
      placeholder: |
        Images or video
      description: |

        Tip: You can attach images or videos by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browser are you using?
      multiple: false
      default: 1
      options:
        - Chrome
        - Safari
        - Brave
        - Arc
        - Firefox
        - Microsoft Edge
        - Other
      validations:
        required: true
  - type: input
    attributes:
      label: If none of the above options apply, please specify your browser here
      placeholder: |
        Your answer
    validations:
      required: false
